[package]
name = "momir_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = "0.16.0"
axum = { version = "0.8.9", features = ["ws"] }
axum-embed = "0.1.0"
chrono = "0.4.45"
grass = "0.13.4"
log = "0.4.33"
native-tls = "0.2.18"
notify = "8.2.0"
rand = "0.10.2"
reqwest = { version = "0.13.4", features = ["query"] }
scryfall_oracle = { version = "0.1.0", path = "../scryfall_oracle" }
sea-orm = { version = "2.0.2", features = [
    "entity-registry",
    "runtime-tokio-native-tls",
    "schema-sync",
    "sqlx-sqlite",
] }
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["full"] }
tower = { version = "0.5.3", features = ["tokio"] }
tower-http = { version = "0.7.0", features = ["fs"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
uuid = { version = "1.25.0", features = ["v4"] }
