[package]
name = "oracle_escpos"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.10"
tempfile = "3.27.0"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
scryfall_oracle = { version = "0.1.0", path = "../scryfall_oracle" }
serde = "1.0.229"
serde_json = "1.0.151"
swash = "0.2.10"
resvg = "0.48.1"
tiny-skia = "0.12.0"
tokio = "1.53.1"
test-log = "0.2.21"
dithr = { version = "0.3.0", features = ["image"] }
async-trait = "0.1.92"
config = "0.15.25"
